### ISSUE TITLE
Livraison des fonctionnalités de base pour la librairie - v0.2

### ISSUE THREAD

**Issue by SamiLetellier** [IQPlay/library#8]
Dans le cadre de la version v0.2, il faut livrer l'ensemble des fonctionnalités prévues pour la librairie.

**Comment by SamiLetellier** [comment]
71375f09889867f94500979e4a66a0e97de31b43

Création de la structure initiale des packages
Implémentation des interfaces et des classes abstraites de base pour le système de jeu.

**Comment by SamiLetellier** [comment]
ad612921f373e8c27afa6fc1df86455d9a762aa2

**Comment by MathieuB-HUB** [comment]
Fonctionnalités de base de la librairie d'aide à la création de jeu intelligent

Coûts :

-36h au total
-12h pour chaque itération, donc 4h/personne
-Nombre d'itération : 3
-3 développeurs sur la feature
